#Zuul config yaml

server:
  port: 8000

zuul:
  ignoredServices: '*' #Zull doesn't register the routes for services registerd in Eureka
  prefix: /api
  routes:
    multiplications:
      path: /multiplications/**
      serviceId: multiplication
      strip-prefix: false
    results:
      path: /results/**
      serviceId: multiplication
      strip-prefix: false
    leaders:
      path: /leaders/**
      serviceId: gamification
      strip-prefix: false
    stats:
      path: /stats/**
      serviceId: gamification
      strip-prefix: false

#endpoints:
#  trace:
#    sensitive: false


management:
  endpoints:
    web:
      exposure:
        include: "*"
    
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka/